import { Medicine, Category, StockLog } from '../types/inventory';
import { Supplier } from '../types/supplier';
import { PurchaseOrder } from '../types/order';
import { NotificationItem } from '../types/notification';
import { User } from '../types/user';

export const MOCK_USER: User = {
  id: 'usr_001',
  name: 'Dr. Sarah Jenkins',
  email: 'sarah.jenkins@medistock.health',
  role: 'Chief Pharmacist',
  avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
  department: 'Central Hospital Pharmacy',
  status: 'Active',
  lastActive: 'Just now',
  phone: '+1 (555) 234-5678',
};

export const MOCK_USERS: User[] = [
  MOCK_USER,
  {
    id: 'usr_002',
    name: 'Marcus Vance',
    email: 'marcus.vance@medistock.health',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    department: 'IT & System Admin',
    status: 'Active',
    lastActive: '5 mins ago',
    phone: '+1 (555) 890-1234',
  },
  {
    id: 'usr_003',
    name: 'Elena Rostova',
    email: 'elena.r@medistock.health',
    role: 'Inventory Manager',
    avatar: 'https://images.unsplash.com/photo-1594824813566-88855ce78907?w=150&auto=format&fit=crop&q=80',
    department: 'Logistics & Supply Chain',
    status: 'Active',
    lastActive: '1 hour ago',
    phone: '+1 (555) 456-7890',
  },
  {
    id: 'usr_004',
    name: 'David Chen',
    email: 'david.chen@medistock.health',
    role: 'Staff Pharmacist',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    department: 'Outpatient Dispensing',
    status: 'Active',
    lastActive: '3 hours ago',
    phone: '+1 (555) 789-0123',
  },
  {
    id: 'usr_005',
    name: 'Amara Okafor',
    email: 'amara.okafor@medistock.health',
    role: 'Staff Pharmacist',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Emergency Care Unit',
    status: 'Pending',
    lastActive: 'Yesterday',
    phone: '+1 (555) 321-6547',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat_1', name: 'Antibiotics & Antimicrobials', itemCount: 142, description: 'Broad-spectrum and targeted bacterial anti-infectives', iconName: 'Pill' },
  { id: 'cat_2', name: 'Cardiovascular Care', itemCount: 98, description: 'Antihypertensives, statins, antiarrhythmics, and antiplatelets', iconName: 'HeartPulse' },
  { id: 'cat_3', name: 'Analgesics & Pain Management', itemCount: 86, description: 'NSAIDs, opioids, antipyretics, and localized anesthetics', iconName: 'Activity' },
  { id: 'cat_4', name: 'Vaccines & Immunology', itemCount: 44, description: 'Biologics, mRNA vaccines, immunosuppressants & serums', iconName: 'Syringe' },
  { id: 'cat_5', name: 'Emergency & Critical Care', itemCount: 67, description: 'Epinephrine, atropine, vasopressors, and emergency IV fluids', iconName: 'Cross' },
  { id: 'cat_6', name: 'Respiratory & Asthma', itemCount: 52, description: 'Bronchodilators, inhaled corticosteroids, and antihistamines', iconName: 'Wind' },
  { id: 'cat_7', name: 'Endocrine & Diabetes Care', itemCount: 79, description: 'Insulins, oral hypoglycemics, thyroid agents, and steroids', iconName: 'Dna' },
];

export const MOCK_MEDICINES: Medicine[] = [
  {
    id: 'MED-1001',
    name: 'Amoxicillin Trihydrate',
    genericName: 'Amoxicillin 500mg',
    category: 'Antibiotics & Antimicrobials',
    supplier: 'BioPharma Global',
    stock: 1450,
    minStockThreshold: 300,
    unit: 'Cap',
    price: 0.85,
    batchNumber: 'BT-88921',
    manufactureDate: '2025-11-10',
    expiryDate: '2027-11-10',
    location: 'Shelf A-12',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Broad-spectrum aminopenicillin antibiotic used for respiratory and sinus infections.',
  },
  {
    id: 'MED-1002',
    name: 'Lipitor (Atorvastatin Calcium)',
    genericName: 'Atorvastatin 20mg',
    category: 'Cardiovascular Care',
    supplier: 'Pfizer Direct',
    stock: 82,
    minStockThreshold: 150,
    unit: 'Tab',
    price: 1.45,
    batchNumber: 'BT-44102',
    manufactureDate: '2024-03-15',
    expiryDate: '2026-08-20',
    location: 'Shelf C-04',
    status: 'Low Stock',
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=300&auto=format&fit=crop&q=80',
    description: 'HMG-CoA reductase inhibitor indicated for hyperlipidemia and cardiac prophylaxis.',
  },
  {
    id: 'MED-1003',
    name: 'Lantus SoloStar Insulin',
    genericName: 'Insulin Glargine 100 U/mL',
    category: 'Endocrine & Diabetes Care',
    supplier: 'Sanofi Healthcare',
    stock: 24,
    minStockThreshold: 50,
    unit: 'Pen',
    price: 42.50,
    batchNumber: 'BT-90112',
    manufactureDate: '2025-01-05',
    expiryDate: '2026-08-15',
    location: 'Cold Storage Room R-2',
    status: 'Near Expiry',
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=300&auto=format&fit=crop&q=80',
    description: 'Long-acting human insulin analog for glycemic control in adult diabetes.',
  },
  {
    id: 'MED-1004',
    name: 'Ventolin HFA Inhaler',
    genericName: 'Albuterol Sulfate 90mcg',
    category: 'Respiratory & Asthma',
    supplier: 'GSK Pharma Corp',
    stock: 310,
    minStockThreshold: 80,
    unit: 'Inhaler',
    price: 28.00,
    batchNumber: 'BT-33290',
    manufactureDate: '2025-06-01',
    expiryDate: '2027-06-01',
    location: 'Shelf B-08',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=300&auto=format&fit=crop&q=80',
    description: 'Beta2-adrenergic agonist for rapid relief of acute bronchospasm.',
  },
  {
    id: 'MED-1005',
    name: 'EpiPen Auto-Injector 0.3mg',
    genericName: 'Epinephrine Injection',
    category: 'Emergency & Critical Care',
    supplier: 'Mylan Specialty',
    stock: 0,
    minStockThreshold: 20,
    unit: 'Injector',
    price: 135.00,
    batchNumber: 'BT-10045',
    manufactureDate: '2024-02-10',
    expiryDate: '2026-06-01',
    location: 'Emergency Cart E-1',
    status: 'Out of Stock',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=300&auto=format&fit=crop&q=80',
    description: 'Emergency parenteral epinephrine for severe allergic reactions / anaphylaxis.',
  },
  {
    id: 'MED-1006',
    name: 'Ciprofloxacin 500mg',
    genericName: 'Ciprofloxacin HCl',
    category: 'Antibiotics & Antimicrobials',
    supplier: 'Novartis International',
    stock: 640,
    minStockThreshold: 200,
    unit: 'Tab',
    price: 1.10,
    batchNumber: 'BT-77213',
    manufactureDate: '2025-08-10',
    expiryDate: '2028-08-10',
    location: 'Shelf A-14',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=300&auto=format&fit=crop&q=80',
    description: 'Fluoroquinolone antibacterial agent for complex urinary and systemic infections.',
  },
  {
    id: 'MED-1007',
    name: 'Ibuprofen 400mg Ultra',
    genericName: 'Ibuprofen',
    category: 'Analgesics & Pain Management',
    supplier: 'BioPharma Global',
    stock: 2200,
    minStockThreshold: 500,
    unit: 'Tab',
    price: 0.25,
    batchNumber: 'BT-55610',
    manufactureDate: '2025-04-01',
    expiryDate: '2028-04-01',
    location: 'Shelf A-02',
    status: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80',
    description: 'Nonsteroidal anti-inflammatory drug (NSAID) for fever and somatic pain.',
  },
  {
    id: 'MED-1008',
    name: 'Comirnaty COVID-19 Vaccine',
    genericName: 'mRNA BNT162b2 30mcg',
    category: 'Vaccines & Immunology',
    supplier: 'Pfizer Direct',
    stock: 18,
    minStockThreshold: 100,
    unit: 'Vial',
    price: 35.00,
    batchNumber: 'BT-99081',
    manufactureDate: '2025-10-01',
    expiryDate: '2026-07-20',
    location: 'Ultra-Low Freezer F-1',
    status: 'Expired',
    imageUrl: 'https://images.unsplash.com/photo-1618961734760-466979ce35b0?w=300&auto=format&fit=crop&q=80',
    description: 'Prophylactic mRNA vaccine formulation against viral respiratory pathogens.',
  },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: 'SUP-01',
    name: 'BioPharma Global Inc.',
    contactPerson: 'Dr. Arthur Pendelton',
    email: 'orders@biopharmaglobal.com',
    phone: '+1 (800) 555-0199',
    address: '450 Innovation Parkway, Cambridge, MA',
    category: 'Antibiotics & General Generics',
    performanceScore: 98.4,
    activeOrders: 4,
    totalSupplied: 145000,
    status: 'Preferred',
    rating: 4.9,
  },
  {
    id: 'SUP-02',
    name: 'Pfizer Direct Distribution',
    contactPerson: 'Claire Standish',
    email: 'supply@pfizerdirect.com',
    phone: '+1 (800) 225-5634',
    address: '235 East 42nd Street, New York, NY',
    category: 'Specialty & Cardiovascular',
    performanceScore: 96.2,
    activeOrders: 2,
    totalSupplied: 320000,
    status: 'Preferred',
    rating: 4.8,
  },
  {
    id: 'SUP-03',
    name: 'Sanofi Healthcare Logistics',
    contactPerson: 'Jean-Luc Moreau',
    email: 'fulfillment@sanofi.org',
    phone: '+1 (888) 443-9081',
    address: '55 Corporate Drive, Bridgewater, NJ',
    category: 'Diabetes & Biologics',
    performanceScore: 91.5,
    activeOrders: 1,
    totalSupplied: 89000,
    status: 'Active',
    rating: 4.5,
  },
  {
    id: 'SUP-04',
    name: 'GSK Pharma Corporation',
    contactPerson: 'Rachel Thornton',
    email: 'contact@gskpharma.co',
    phone: '+1 (800) 368-5868',
    address: '709 Swedeland Road, King of Prussia, PA',
    category: 'Respiratory & Pulmonology',
    performanceScore: 94.8,
    activeOrders: 3,
    totalSupplied: 178000,
    status: 'Active',
    rating: 4.7,
  },
  {
    id: 'SUP-05',
    name: 'Mylan Specialty Products',
    contactPerson: 'Kevin Patel',
    email: 'b2b@mylanspecialty.com',
    phone: '+1 (800) 796-9526',
    address: '1000 Mylan Boulevard, Canonsburg, PA',
    category: 'Emergency & Injection Devices',
    performanceScore: 84.0,
    activeOrders: 0,
    totalSupplied: 45000,
    status: 'Under Review',
    rating: 3.9,
  },
];

export const MOCK_ORDERS: PurchaseOrder[] = [
  {
    id: 'PO-2026-8801',
    orderNumber: 'PO-8801',
    supplierId: 'SUP-01',
    supplierName: 'BioPharma Global Inc.',
    itemsCount: 5,
    totalAmount: 14250.00,
    status: 'Delivered',
    orderedDate: '2026-07-15',
    expectedDelivery: '2026-07-20',
    createdByName: 'Dr. Sarah Jenkins',
    items: [
      { medicineName: 'Amoxicillin Trihydrate', quantity: 10000, unitPrice: 0.85 },
      { medicineName: 'Ibuprofen 400mg Ultra', quantity: 20000, unitPrice: 0.25 },
    ]
  },
  {
    id: 'PO-2026-8802',
    orderNumber: 'PO-8802',
    supplierId: 'SUP-02',
    supplierName: 'Pfizer Direct Distribution',
    itemsCount: 3,
    totalAmount: 28900.50,
    status: 'Shipped',
    orderedDate: '2026-07-22',
    expectedDelivery: '2026-07-29',
    createdByName: 'Elena Rostova',
    items: [
      { medicineName: 'Lipitor (Atorvastatin Calcium)', quantity: 2000, unitPrice: 1.45 }
    ]
  },
  {
    id: 'PO-2026-8803',
    orderNumber: 'PO-8803',
    supplierId: 'SUP-03',
    supplierName: 'Sanofi Healthcare Logistics',
    itemsCount: 2,
    totalAmount: 8500.00,
    status: 'Approved',
    orderedDate: '2026-07-25',
    expectedDelivery: '2026-07-31',
    createdByName: 'Dr. Sarah Jenkins',
  },
  {
    id: 'PO-2026-8804',
    orderNumber: 'PO-8804',
    supplierId: 'SUP-05',
    supplierName: 'Mylan Specialty Products',
    itemsCount: 1,
    totalAmount: 6750.00,
    status: 'Pending',
    orderedDate: '2026-07-26',
    expectedDelivery: '2026-08-03',
    createdByName: 'Elena Rostova',
  },
];

export const MOCK_STOCK_LOGS: StockLog[] = [
  {
    id: 'LOG-9941',
    medicineId: 'MED-1001',
    medicineName: 'Amoxicillin Trihydrate',
    type: 'Stock In',
    quantity: 500,
    previousStock: 950,
    newStock: 1450,
    performedBy: 'David Chen',
    timestamp: '2026-07-27 10:14:00',
    reason: 'Received shipment batch BT-88921 from BioPharma',
  },
  {
    id: 'LOG-9940',
    medicineId: 'MED-1003',
    medicineName: 'Lantus SoloStar Insulin',
    type: 'Stock Out',
    quantity: 6,
    previousStock: 30,
    newStock: 24,
    performedBy: 'Dr. Sarah Jenkins',
    timestamp: '2026-07-27 09:30:00',
    reason: 'Dispensed to Ward B Intensive Care Unit',
  },
  {
    id: 'LOG-9939',
    medicineId: 'MED-1005',
    medicineName: 'EpiPen Auto-Injector 0.3mg',
    type: 'Stock Out',
    quantity: 10,
    previousStock: 10,
    newStock: 0,
    performedBy: 'Elena Rostova',
    timestamp: '2026-07-26 16:45:00',
    reason: 'Emergency ER replenishment callout',
  },
  {
    id: 'LOG-9938',
    medicineId: 'MED-1008',
    medicineName: 'Comirnaty COVID-19 Vaccine',
    type: 'Disposed',
    quantity: 15,
    previousStock: 33,
    newStock: 18,
    performedBy: 'Marcus Vance',
    timestamp: '2026-07-25 14:10:00',
    reason: 'Cold chain temperature deviation write-off',
  },
  {
    id: 'LOG-9937',
    medicineId: 'MED-1007',
    medicineName: 'Ibuprofen 400mg Ultra',
    type: 'Adjustment',
    quantity: 200,
    previousStock: 2000,
    newStock: 2200,
    performedBy: 'Amara Okafor',
    timestamp: '2026-07-24 11:20:00',
    reason: 'Routine quarterly audit reconciliation',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Out of Stock Alert',
    message: 'EpiPen Auto-Injector 0.3mg reached 0 units. Immediate reorder suggested.',
    timestamp: '10 mins ago',
    type: 'alert',
    read: false,
    category: 'Stock',
  },
  {
    id: 'notif-2',
    title: 'Near Expiry Notice',
    message: 'Lantus SoloStar Insulin (Batch BT-90112) expires in 19 days.',
    timestamp: '1 hour ago',
    type: 'warning',
    read: false,
    category: 'Expiry',
  },
  {
    id: 'notif-3',
    title: 'Shipment Dispatched',
    message: 'Purchase Order PO-8802 (Pfizer Direct) is now in transit.',
    timestamp: '3 hours ago',
    type: 'info',
    read: true,
    category: 'Order',
  },
  {
    id: 'notif-4',
    title: 'Stock Audit Verified',
    message: 'Quarterly inventory audit for Antibiotics finished with 99.8% precision.',
    timestamp: 'Yesterday',
    type: 'success',
    read: true,
    category: 'System',
  },
];

export const MOCK_MONTHLY_ANALYTICS = [
  { month: 'Jan', stockIn: 4500, stockOut: 3200, orders: 12000 },
  { month: 'Feb', stockIn: 5200, stockOut: 3900, orders: 15400 },
  { month: 'Mar', stockIn: 6100, stockOut: 4400, orders: 18900 },
  { month: 'Apr', stockIn: 5800, stockOut: 4800, orders: 16200 },
  { month: 'May', stockIn: 7400, stockOut: 5300, orders: 22100 },
  { month: 'Jun', stockIn: 6900, stockOut: 5600, orders: 20400 },
  { month: 'Jul', stockIn: 8300, stockOut: 6100, orders: 25800 },
];
